apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: salesvision-web
  annotations:
    run.googleapis.com/ingress: all # internal-and-cloud-load-balancing   # 🔒 restrict public access
    run.googleapis.com/description: "Next.js frontend for SalesVision"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/client-name: "gcloud"
    spec:
      containers:
        - image: gcr.io/youngintlsaleswebapp/salesvision-web:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://TODO-api-url.example.com"

            - name: NODE_ENV
              value: "production"
            - name: SESSION_COOKIE_NAME
              value: "sid"

          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
  traffic:
    - latestRevision: true
      percent: 100
