steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/youngintlsaleswebapp/sales-vision/web:latest', '-f', 'apps/web/Dockerfile', '.' ]
images:
  - 'us-central1-docker.pkg.dev/youngintlsaleswebapp/sales-vision/web:latest'
