version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ../apps/api
    env_file:
      - ../.env.example
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@db:5432/appdb
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: ../apps/web
    env_file:
      - ../.env.example
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    depends_on:
      - api
    ports:
      - "3000:3000"
    command: npm run dev -- --hostname 0.0.0.0 --port 3000

volumes:
  dbdata:
