"""enforce_all_fks_and_audit

Revision ID: 6d4def5fc465
Revises: f99bd1eb4948
Create Date: 2025-12-24 17:49:10.182743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4def5fc465'
down_revision: Union[str, Sequence[str], None] = 'f99bd1eb4948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flows', sa.Column('client_number', sa.String(length=50), nullable=True))
    op.add_column('cash_flows', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('cash_flows', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('cash_flows', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('cash_flows', 'staff',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_cash_flows_client_number'), 'cash_flows', ['client_number'], unique=False)
    op.create_foreign_key(None, 'cash_flows', 'clients', ['client_number'], ['client_number'])
    op.create_foreign_key(None, 'cash_flows', 'employees', ['staff'], ['staff_number'])
    op.add_column('cheques', sa.Column('client_number', sa.String(length=50), nullable=True))
    op.add_column('cheques', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('cheques', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('cheques', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('cheques', 'staff',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_cheques_client_number'), 'cheques', ['client_number'], unique=False)
    op.create_foreign_key(None, 'cheques', 'employees', ['staff'], ['staff_number'])
    op.create_foreign_key(None, 'cheques', 'clients', ['client_number'], ['client_number'])
    op.add_column('clients', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('commissions', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('commissions', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('commissions', sa.Column('version_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'commissions', 'employees', ['staff_number'], ['staff_number'])
    op.add_column('credits', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('credits', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('credits', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('credits', 'staff',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'credits', 'clients', ['client_number'], ['client_number'])
    op.create_foreign_key(None, 'credits', 'employees', ['staff'], ['staff_number'])
    op.add_column('employees', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('expenditures', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('expenditures', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('expenditures', sa.Column('version_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'expenditures', 'products', ['product_code'], ['product_code'])
    op.add_column('monthly_sales_targets', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('monthly_sales_targets', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('monthly_sales_targets', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('monthly_sales_targets', 'staff',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'monthly_sales_targets', 'products', ['product_code'], ['product_code'])
    op.create_foreign_key(None, 'monthly_sales_targets', 'employees', ['staff'], ['staff_number'])
    op.add_column('overdue_collections', sa.Column('client_number', sa.String(length=50), nullable=True))
    op.add_column('overdue_collections', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('overdue_collections', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('overdue_collections', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('overdue_collections', 'staff',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_overdue_collections_client_number'), 'overdue_collections', ['client_number'], unique=False)
    op.create_foreign_key(None, 'overdue_collections', 'clients', ['client_number'], ['client_number'])
    op.create_foreign_key(None, 'overdue_collections', 'employees', ['staff'], ['staff_number'])
    op.add_column('price_lists', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('price_lists', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('price_lists', sa.Column('version_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'price_lists', 'products', ['product_code'], ['product_code'])
    op.add_column('products', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('sales', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('sales', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('sales', 'staff',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_foreign_key(None, 'sales', 'employees', ['staff'], ['staff_number'])
    op.create_foreign_key(None, 'sales', 'products', ['product_code'], ['product_code'])
    op.create_foreign_key(None, 'sales', 'clients', ['client_number'], ['client_number'])
    op.add_column('stocks', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('stocks', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('stocks', sa.Column('version_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stocks', 'products', ['product_code'], ['product_code'])
    op.add_column('users', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['staff_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'version_id')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'version_id')
    op.drop_column('stocks', 'updated_by')
    op.drop_column('stocks', 'created_by')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.alter_column('sales', 'staff',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('sales', 'version_id')
    op.drop_column('sales', 'updated_by')
    op.drop_column('sales', 'created_by')
    op.drop_column('products', 'version_id')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_constraint(None, 'price_lists', type_='foreignkey')
    op.drop_column('price_lists', 'version_id')
    op.drop_column('price_lists', 'updated_by')
    op.drop_column('price_lists', 'created_by')
    op.drop_constraint(None, 'overdue_collections', type_='foreignkey')
    op.drop_constraint(None, 'overdue_collections', type_='foreignkey')
    op.drop_index(op.f('ix_overdue_collections_client_number'), table_name='overdue_collections')
    op.alter_column('overdue_collections', 'staff',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('overdue_collections', 'version_id')
    op.drop_column('overdue_collections', 'updated_by')
    op.drop_column('overdue_collections', 'created_by')
    op.drop_column('overdue_collections', 'client_number')
    op.drop_constraint(None, 'monthly_sales_targets', type_='foreignkey')
    op.drop_constraint(None, 'monthly_sales_targets', type_='foreignkey')
    op.alter_column('monthly_sales_targets', 'staff',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('monthly_sales_targets', 'version_id')
    op.drop_column('monthly_sales_targets', 'updated_by')
    op.drop_column('monthly_sales_targets', 'created_by')
    op.drop_constraint(None, 'expenditures', type_='foreignkey')
    op.drop_column('expenditures', 'version_id')
    op.drop_column('expenditures', 'updated_by')
    op.drop_column('expenditures', 'created_by')
    op.drop_column('employees', 'version_id')
    op.drop_column('employees', 'updated_by')
    op.drop_column('employees', 'created_by')
    op.drop_constraint(None, 'credits', type_='foreignkey')
    op.drop_constraint(None, 'credits', type_='foreignkey')
    op.alter_column('credits', 'staff',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('credits', 'version_id')
    op.drop_column('credits', 'updated_by')
    op.drop_column('credits', 'created_by')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_column('commissions', 'version_id')
    op.drop_column('commissions', 'updated_by')
    op.drop_column('commissions', 'created_by')
    op.drop_column('clients', 'version_id')
    op.drop_column('clients', 'updated_by')
    op.drop_column('clients', 'created_by')
    op.drop_constraint(None, 'cheques', type_='foreignkey')
    op.drop_constraint(None, 'cheques', type_='foreignkey')
    op.drop_index(op.f('ix_cheques_client_number'), table_name='cheques')
    op.alter_column('cheques', 'staff',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('cheques', 'version_id')
    op.drop_column('cheques', 'updated_by')
    op.drop_column('cheques', 'created_by')
    op.drop_column('cheques', 'client_number')
    op.drop_constraint(None, 'cash_flows', type_='foreignkey')
    op.drop_constraint(None, 'cash_flows', type_='foreignkey')
    op.drop_index(op.f('ix_cash_flows_client_number'), table_name='cash_flows')
    op.alter_column('cash_flows', 'staff',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('cash_flows', 'version_id')
    op.drop_column('cash_flows', 'updated_by')
    op.drop_column('cash_flows', 'created_by')
    op.drop_column('cash_flows', 'client_number')
    # ### end Alembic commands ###
