"""Add foreign key from user to employee

Revision ID: b1596a37a8f1
Revises: f99bd1eb4948
Create Date: 2025-11-15 22:24:39.979815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1596a37a8f1'
down_revision: Union[str, Sequence[str], None] = 'f99bd1eb4948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'credits', 'employees', ['staff'], ['name'])
    op.create_foreign_key(None, 'credits', 'clients', ['client_number'], ['client_number'])
    op.create_foreign_key(None, 'overdue_collections', 'employees', ['staff'], ['name'])
    op.create_foreign_key(None, 'overdue_collections', 'clients', ['client_name'], ['client_name'])
    op.create_foreign_key(None, 'sales', 'products', ['product_code'], ['product_code'])
    op.create_foreign_key(None, 'sales', 'clients', ['client_number'], ['client_number'])
    op.create_foreign_key(None, 'sales', 'employees', ['staff'], ['name'])
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['staff_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'overdue_collections', type_='foreignkey')
    op.drop_constraint(None, 'overdue_collections', type_='foreignkey')
    op.drop_constraint(None, 'credits', type_='foreignkey')
    op.drop_constraint(None, 'credits', type_='foreignkey')
    # ### end Alembic commands ###
