"""Initial schema with 14 tables

Revision ID: f99bd1eb4948
Revises: 
Create Date: 2025-11-15 18:59:27.623000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99bd1eb4948'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('cash_origin', sa.String(length=100), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment', sa.String(length=100), nullable=True),
    sa.Column('payment_product', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_expenditure', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('weekly_review', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_flows_client_name'), 'cash_flows', ['client_name'], unique=False)
    op.create_index(op.f('ix_cash_flows_date'), 'cash_flows', ['date'], unique=False)
    op.create_index(op.f('ix_cash_flows_staff'), 'cash_flows', ['staff'], unique=False)
    op.create_table('cheques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receipt_date', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('issue_bank', sa.String(length=255), nullable=True),
    sa.Column('cheque_number', sa.String(length=100), nullable=True),
    sa.Column('deposit_bank', sa.String(length=255), nullable=True),
    sa.Column('deposit_date', sa.String(length=50), nullable=True),
    sa.Column('cheque_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('approval_status', sa.String(length=100), nullable=True),
    sa.Column('weekly_review', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheques_cheque_number'), 'cheques', ['cheque_number'], unique=True)
    op.create_index(op.f('ix_cheques_client_name'), 'cheques', ['client_name'], unique=False)
    op.create_index(op.f('ix_cheques_due_date'), 'cheques', ['due_date'], unique=False)
    op.create_index(op.f('ix_cheques_receipt_date'), 'cheques', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_cheques_staff'), 'cheques', ['staff'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_category', sa.String(length=100), nullable=True),
    sa.Column('client_grade', sa.String(length=10), nullable=True),
    sa.Column('clients_type', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_position', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name2', sa.String(length=255), nullable=True),
    sa.Column('contact_position2', sa.String(length=100), nullable=True),
    sa.Column('contact_phone2', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('average_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('yearly_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_grade'), 'clients', ['client_grade'], unique=False)
    op.create_index(op.f('ix_clients_client_name'), 'clients', ['client_name'], unique=False)
    op.create_index(op.f('ix_clients_client_number'), 'clients', ['client_number'], unique=True)
    op.create_index(op.f('ix_clients_staff'), 'clients', ['staff'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_number', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('commission', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('monthly_review', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('clients_type', sa.String(length=100), nullable=True),
    sa.Column('import_product', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('local_product', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('client_transfer_calculation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_staff'), 'commissions', ['staff'], unique=False)
    op.create_index(op.f('ix_commissions_staff_number'), 'commissions', ['staff_number'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('client_number', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_payment_type', sa.String(length=50), nullable=True),
    sa.Column('credit_due_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_client_name'), 'credits', ['client_name'], unique=False)
    op.create_index(op.f('ix_credits_client_number'), 'credits', ['client_number'], unique=False)
    op.create_index(op.f('ix_credits_credit_due_date'), 'credits', ['credit_due_date'], unique=False)
    op.create_index(op.f('ix_credits_date'), 'credits', ['date'], unique=False)
    op.create_index(op.f('ix_credits_staff'), 'credits', ['staff'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_number', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('working_start', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('emergency_call', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_staff_number'), 'employees', ['staff_number'], unique=True)
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('payment_way', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('expenditure_category', sa.String(length=100), nullable=True),
    sa.Column('receipt_availability', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenditures_date'), 'expenditures', ['date'], unique=False)
    op.create_index(op.f('ix_expenditures_expenditure_category'), 'expenditures', ['expenditure_category'], unique=False)
    op.create_index(op.f('ix_expenditures_product_code'), 'expenditures', ['product_code'], unique=False)
    op.create_table('monthly_sales_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('sales_amount_minus_3_month', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sales_amount_minus_2_month', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sales_amount_minus_1_month', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sales_monthly_target', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('company_target', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_sales_targets_product_code'), 'monthly_sales_targets', ['product_code'], unique=False)
    op.create_index(op.f('ix_monthly_sales_targets_staff'), 'monthly_sales_targets', ['staff'], unique=False)
    op.create_table('overdue_collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('credit_period', sa.Integer(), nullable=True),
    sa.Column('credit_amount', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overdue_collections_client_name'), 'overdue_collections', ['client_name'], unique=False)
    op.create_index(op.f('ix_overdue_collections_date'), 'overdue_collections', ['date'], unique=False)
    op.create_index(op.f('ix_overdue_collections_staff'), 'overdue_collections', ['staff'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('client_grade', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_client_grade'), 'price_lists', ['client_grade'], unique=False)
    op.create_index(op.f('ix_price_lists_product_code'), 'price_lists', ['product_code'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('creditor_cash', sa.String(length=50), nullable=True),
    sa.Column('amount_credit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('upload_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_category'), 'products', ['product_category'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_in_out', sa.String(length=50), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('invoice', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('client_grade', sa.String(length=10), nullable=True),
    sa.Column('client_number', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('staff', sa.String(length=255), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_client_name'), 'sales', ['client_name'], unique=False)
    op.create_index(op.f('ix_sales_client_number'), 'sales', ['client_number'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_index(op.f('ix_sales_invoice'), 'sales', ['invoice'], unique=False)
    op.create_index(op.f('ix_sales_product_code'), 'sales', ['product_code'], unique=False)
    op.create_index(op.f('ix_sales_staff'), 'sales', ['staff'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=500), nullable=True),
    sa.Column('average_sales_quantity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('duration_period', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('check_date', sa.String(length=50), nullable=True),
    sa.Column('monthly_review', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_product_category'), 'stocks', ['product_category'], unique=False)
    op.create_index(op.f('ix_stocks_product_code'), 'stocks', ['product_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_product_code'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_product_category'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_sales_staff'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_code'), table_name='sales')
    op.drop_index(op.f('ix_sales_invoice'), table_name='sales')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_client_number'), table_name='sales')
    op.drop_index(op.f('ix_sales_client_name'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_product_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_price_lists_product_code'), table_name='price_lists')
    op.drop_index(op.f('ix_price_lists_client_grade'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_overdue_collections_staff'), table_name='overdue_collections')
    op.drop_index(op.f('ix_overdue_collections_date'), table_name='overdue_collections')
    op.drop_index(op.f('ix_overdue_collections_client_name'), table_name='overdue_collections')
    op.drop_table('overdue_collections')
    op.drop_index(op.f('ix_monthly_sales_targets_staff'), table_name='monthly_sales_targets')
    op.drop_index(op.f('ix_monthly_sales_targets_product_code'), table_name='monthly_sales_targets')
    op.drop_table('monthly_sales_targets')
    op.drop_index(op.f('ix_expenditures_product_code'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_expenditure_category'), table_name='expenditures')
    op.drop_index(op.f('ix_expenditures_date'), table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index(op.f('ix_employees_staff_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_credits_staff'), table_name='credits')
    op.drop_index(op.f('ix_credits_date'), table_name='credits')
    op.drop_index(op.f('ix_credits_credit_due_date'), table_name='credits')
    op.drop_index(op.f('ix_credits_client_number'), table_name='credits')
    op.drop_index(op.f('ix_credits_client_name'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_commissions_staff_number'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_staff'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_clients_staff'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_grade'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_cheques_staff'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_receipt_date'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_due_date'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_client_name'), table_name='cheques')
    op.drop_index(op.f('ix_cheques_cheque_number'), table_name='cheques')
    op.drop_table('cheques')
    op.drop_index(op.f('ix_cash_flows_staff'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_date'), table_name='cash_flows')
    op.drop_index(op.f('ix_cash_flows_client_name'), table_name='cash_flows')
    op.drop_table('cash_flows')
    # ### end Alembic commands ###
